<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Configuracao extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Configuracao_model');
    } 

    /*
     * Editing A configuração
     */
    function index($ID_Configuracao = 1)
    {   
        // check if the configuracao exists before trying to edit it
        $data['configuracao'] = $this->Configuracao_model->get_configuracao($ID_Configuracao);
        
        if(isset($data['configuracao']['ID_Configuracao']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Nome_Fantasia','Nome Fantasia','required');
		    $this->form_validation->set_rules('CNPJ_CPF','CNPJ / CPF','required|numeric|min_length[11]|max_length[14]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'CNPJ_CPF' => $this->input->post('CNPJ_CPF'),
                    'Nome_Fantasia' => $this->input->post('Nome_Fantasia'),
                    'Endereco' => $this->input->post('Endereco'),
                    'CPF_Obrigatorio' => $this->input->post('CPF_Obrigatorio'),
                    'CPF_Obrigatorio' => $this->input->post('CPF_Obrigatorio'),
                    'Habilitar_Parcelamento' => $this->input->post('Habilitar_Parcelamento'),
                    'Habilitar_Cartao' => $this->input->post('Habilitar_Cartao'),
                    'Telefone' => $this->input->post('Telefone'),
                    'Celular' => $this->input->post('Celular'),
                    'Cidade' => $this->input->post('Cidade'),
                    'UF' => $this->input->post('UF'),
                    'Incluir_Juros_Pagamento_Parcial' => $this->input->post('Incluir_Juros_Pagamento_Parcial'),
                );

                $this->Configuracao_model->update_configuracao($ID_Configuracao,$params);            
                redirect('configuracao/index');
            }
            else
            {
                $data['_view'] = 'configuracao/index';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('A configuração que você está tentando acessar não existe.');
    } 

    
}
