<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Investidor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Investidor_model');
    } 

    /*
     * Listing of investidor
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('investidor/index?');
        $config['total_rows'] = $this->Investidor_model->get_all_investidor_count();
        $this->pagination->initialize($config);

        $data['investidor'] = $this->Investidor_model->get_all_investidor($params);
        
        $data['_view'] = 'investidor/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new investidor
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('Nome_Investidor','Nome Investidor','required');
		$this->form_validation->set_rules('RG','RG','required|numeric');
        $this->form_validation->set_rules('CPF','CPF','required|numeric');
        $this->form_validation->set_rules('Celular','Celular','required|numeric');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'Nome_Investidor' => $this->input->post('Nome_Investidor'),
				'Rua' => $this->input->post('Rua'),
				'RG' => $this->input->post('RG'),
				'CPF' => $this->input->post('CPF'),
				'Bairro' => $this->input->post('Bairro'),
				'Numero' => $this->input->post('Numero'),
				'Telefone' => $this->input->post('Telefone'),
				'Celular' => $this->input->post('Celular'),
				'Email' => $this->input->post('Email'),
                'Profissao' => $this->input->post('Profissao'),
                'Local_Trabalho' => $this->input->post('Local_Trabalho'),
                'Tempo_Servico' => $this->input->post('Tempo_Servico'),
                'Salario_Atual' => $this->input->post('Salario_Atual'),
                'Data_Admissao' => convertDateYmd($this->input->post('Data_Admissao')),
                'Limite_Credito' => $this->input->post('Limite_Credito'),
                'Data_Serasa' => convertDateYmd($this->input->post('Data_Serasa')),
                'Pendencia_Bancaria' => $this->input->post('Pendencia_Bancaria'),
                'Pendencia_Banco' => $this->input->post('Pendencia_Banco'),
                'Pendencia_Valor' => $this->input->post('Pendencia_Valor'),
                'Cidade' => $this->input->post('Cidade'),
                'UF' => $this->input->post('UF'),
                'Bloqueio_Serasa' => $this->input->post('Bloqueio_Serasa'),
                'Observacao' => $this->input->post('Observacao'),
                'ID_User_Create' => $this->session->userdata['user_id'],
                'Date_Created' => Date('Y/m/d H:i:s'),
                'ID_User_Update' => $this->session->userdata['user_id'],
                'Date_Updated' => Date('Y/m/d H:i:s'),
            );
            
            $investidor_id = $this->Investidor_model->add_investidor($params);
            redirect('investidor/index');
        }
        else
        {            
            $data['_view'] = 'investidor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a investidor
     */
    function edit($ID_Investidor)
    {   
        // check if the investidor exists before trying to edit it
        $data['investidor'] = $this->Investidor_model->get_investidor($ID_Investidor);

        $tempo_servico_anos = diferencaEmAnos($data['investidor']['Data_Admissao'], Date('Y-m-d'));
        $data['tempo_servico'] = $tempo_servico_anos . ' ano(s)';
        // if ($tempo_servico_anos < 1) {
        //     $tempo_servico_meses = diferencaEmMeses($data['investidor']['Data_Admissao'], Date('Y-m-d'));
        //     $data['tempo_servico'] = $tempo_servico_meses > 1 ? $tempo_servico_meses . ' Meses' : $tempo_servico_meses . ' Mês';
        // }
        
        if(isset($data['investidor']['ID_Investidor']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Nome_Investidor','Nome Investidor','required');
            $this->form_validation->set_rules('RG','RG','required|numeric');
            $this->form_validation->set_rules('CPF','CPF','required|numeric');
            $this->form_validation->set_rules('Celular','Celular','required|numeric');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'Nome_Investidor' => $this->input->post('Nome_Investidor'),
                    'RG' => $this->input->post('RG'),
				    'CPF' => $this->input->post('CPF'),
					'Rua' => $this->input->post('Rua'),
					'Bairro' => $this->input->post('Bairro'),
					'Numero' => $this->input->post('Numero'),
					'Telefone' => $this->input->post('Telefone'),
					'Celular' => $this->input->post('Celular'),
					'Email' => $this->input->post('Email'),
                    'Profissao' => $this->input->post('Profissao'),
                    'Local_Trabalho' => $this->input->post('Local_Trabalho'),
                    'Tempo_Servico' => $this->input->post('Tempo_Servico'),
                    'Salario_Atual' => $this->input->post('Salario_Atual'),
                    'Data_Admissao' => convertDateYmd($this->input->post('Data_Admissao')),
                    'Limite_Credito' => $this->input->post('Limite_Credito'),
                    'Data_Serasa' => convertDateYmd($this->input->post('Data_Serasa')),
                    'Pendencia_Bancaria' => $this->input->post('Pendencia_Bancaria'),
                    'Pendencia_Banco' => $this->input->post('Pendencia_Banco'),
                    'Pendencia_Valor' => $this->input->post('Pendencia_Valor'),
                    'Cidade' => $this->input->post('Cidade'),
                    'UF' => $this->input->post('UF'),
                    'Bloqueio_Serasa' => $this->input->post('Bloqueio_Serasa'),
                    'Observacao' => $this->input->post('Observacao'),
                    'ID_User_Update' => $this->session->userdata['user_id'],
                'Date_Updated' => Date('Y/m/d H:i:s'),
                );

                $this->Investidor_model->update_investidor($ID_Investidor,$params);            
                redirect('investidor/index');
            }
            else
            {
                $data['_view'] = 'investidor/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('O investidor que você está tentando acessar não existe.');
    } 

    /*
     * Deleting investidor
     */
    function remove($ID_Investidor)
    {
        $investidor = $this->Investidor_model->get_investidor($ID_Investidor);

        // check if the investidor exists before trying to delete it
        if(isset($investidor['ID_Investidor']))
        {
            $this->Investidor_model->delete_investidor($ID_Investidor);
            redirect('investidor/index');
        }
        else
            show_error('O investidor que você está tentando deletar não existe.');
    }
    
}
