<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Observacao_parcela extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Observacao_emprestimo_model');
    } 

    /*
     * Listing of observacao_emprestimo
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('observacao_emprestimo/index?');
        $config['total_rows'] = $this->Observacao_emprestimo_model->get_all_observacao_emprestimo_count();
        $this->pagination->initialize($config);

        $data['observacao_emprestimo'] = $this->Observacao_emprestimo_model->get_all_observacao_emprestimo($params);
        
        $data['_view'] = 'observacao_emprestimo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new observacao_emprestimo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('Observacao_Emprestimo','Observacao Parcela','required');
		$this->form_validation->set_rules('ID_Parcela','ID Parcela','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'ID_Parcela' => $this->input->post('ID_Parcela'),
				'Observacao_Emprestimo' => $this->input->post('Observacao_Emprestimo'),
            );
            
            $observacao_emprestimo_id = $this->Observacao_emprestimo_model->add_observacao_emprestimo($params);
            redirect('observacao_emprestimo/index');
        }
        else
        {
			$this->load->model('Renegociacao_parcela_model');
			$data['all_renegociacao_parcela'] = $this->Renegociacao_parcela_model->get_all_renegociacao_parcela();
            
            $data['_view'] = 'observacao_emprestimo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a observacao_emprestimo
     */
    function edit($ID_Observacao_Emprestimo)
    {   
        // check if the observacao_emprestimo exists before trying to edit it
        $data['observacao_emprestimo'] = $this->Observacao_emprestimo_model->get_observacao_emprestimo($ID_Observacao_Emprestimo);
        
        if(isset($data['observacao_emprestimo']['ID_Observacao_Emprestimo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Observacao_Emprestimo','Observacao Parcela','required');
			$this->form_validation->set_rules('ID_Parcela','ID Parcela','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'ID_Parcela' => $this->input->post('ID_Parcela'),
					'Observacao_Emprestimo' => $this->input->post('Observacao_Emprestimo'),
                );

                $this->Observacao_emprestimo_model->update_observacao_emprestimo($ID_Observacao_Emprestimo,$params);            
                redirect('observacao_emprestimo/index');
            }
            else
            {
				$this->load->model('Renegociacao_parcela_model');
				$data['all_renegociacao_parcela'] = $this->Renegociacao_parcela_model->get_all_renegociacao_parcela();

                $data['_view'] = 'observacao_emprestimo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('A observação da parcela que você está tentando acessar não existe.');
    } 

    /*
     * Deleting observacao_emprestimo
     */
    function remove($ID_Observacao_Emprestimo)
    {
        $observacao_emprestimo = $this->Observacao_emprestimo_model->get_observacao_emprestimo($ID_Observacao_Emprestimo);

        // check if the observacao_emprestimo exists before trying to delete it
        if(isset($observacao_emprestimo['ID_Observacao_Emprestimo']))
        {
            $this->Observacao_emprestimo_model->delete_observacao_emprestimo($ID_Observacao_Emprestimo);
            redirect('observacao_emprestimo/index');
        }
        else
            show_error('A observação da parcela que você está tentando deletar não existe.');
    }
    
}
