<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rota extends CI_Controller {

    function __construct()
    {
        parent::__construct();
        $this->load->model('Rota_model');

        //$this->output->enable_profiler(TRUE);
    } 
    

    function filtrar($page = 'index') {

        //Este método apenas irá definir como filtro todos os campos que foram postados e redirecionar para a página desejada        
        $filtro = $_POST;

        $this->session->set_flashdata('filtro', $filtro);
        redirect('rota/'.$page);

    }

    function listar_filtros($filtro = array()) {

        $filtro = array_filter($filtro, 'strlen');

        foreach ($filtro as $chave => $valor) {
            $lista[] = str_replace('_',' ', $chave) . ': <b>' . str_replace('-', '~', $valor) . '</b>';
        }

        return implode(' / ', $lista) ?: [];

    }

    /*
     * Listing of emprestimo
     */
    function index()
    {

        $hoje_ou_proximo_dia_util = Date('w') == 6 ?  Date('d/m/Y', strtotime(Date('Y/m/d') . " +2 day")) : (Date('w') == 0 ? Date('d/m/Y', strtotime(Date('Y/m/d') . " +1 day") ) : Date('d/m/Y')  );
        $data['hoje_ou_proximo_dia_util'] = $hoje_ou_proximo_dia_util;
        
        // Se o usuário for do tipo cobrador então filtra apenas a cidade dele
        $cidade = $this->ion_auth->is_cobrador() ? $this->session->userdata['city'] : null;

        //Para utilizar filtros é necessário adicionar esse snippet ao metodo do controller sempre e também adicionar o metodo filtrar [a exemplo deste controller]
        $data['filtro'] = $this->session->flashdata('filtro');
        if(isset($data['filtro']) && !empty($data['filtro'])) {
            $params['filtro'] = $this->session->flashdata('filtro');
            $ativar_paginacao = false;
        } else {
            $params['filtro'] = [ 'Data_Pagamento' => $hoje_ou_proximo_dia_util ];
            $ativar_paginacao = false;
        }

        //Caso exista filtro, desativar paginação
        if ($ativar_paginacao) {
            $params['limit'] = RECORDS_PER_PAGE; 
            $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
            $config = $this->config->item('pagination');
            $config['base_url'] = site_url('rota/index?');
            $config['total_rows'] = $this->Rota_model->get_rotas_count($params, $cidade);
            $this->pagination->initialize($config);
        }


        $data['rotas'] = $this->Rota_model->get_rotas($params, $cidade);

        $data['_view'] = 'rota/index';
        $this->load->view('layouts/main',$data);
    }
    

}