<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Configuracao_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get configuracao by ID_Configuracao
     */
    function get_configuracao($ID_Configuracao = 1)
    {
        return $this->db->get_where('configuracao',array('ID_Configuracao'=>$ID_Configuracao))->row_array();
    }
    
    /*
     * function to update configuracao
     */
    function update_configuracao($ID_Configuracao = 1,$params)
    {
        $this->db->where('ID_Configuracao',$ID_Configuracao);
        return $this->db->update('configuracao',$params);
    }
    
}
