<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Conta_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get conta by ID_Conta
     */
    function get_conta($ID_Conta)
    {
        return $this->db->get_where('conta',array('ID_Conta'=>$ID_Conta))->row_array();
    }
        
    /*
     * Get all conta
     */
    function get_all_conta()
    {
        $this->db->order_by('ID_Conta', 'desc');
        return $this->db->get('conta')->result_array();
    }
       
    function get_history_conta($ID_Conta) {

        $id_conta_investimento = 1;
        $id_conta_lucro = 2;

        //Mostra as saídas de emprestimo e apenas as entradas de retorno
        if ($ID_Conta == $id_conta_investimento) {

            $query = $this->db->query("
                SELECT a.ID_Emprestimo, a.ID_Emprestimo_Pai, b.ID_Investidor, b.Nome_Investidor, SUM(Valor_Emprestimo) as Valor, Data_Emprestimo as Data, 'E' as Tipo 
                FROM emprestimo a, investidor b 
                WHERE a.ID_Investidor = b.ID_Investidor 
                GROUP BY Data 
                UNION ALL
                SELECT c.ID_Emprestimo,  d.ID_Emprestimo_Pai, e.ID_Investidor, e.Nome_Investidor, Valor_Retorno_Pagamento as Valor, c.Data_Pagamento as Data, 'P' as Tipo 
                FROM pagamento c, emprestimo d, investidor e 
                WHERE c.ID_Emprestimo = d.ID_Emprestimo AND d.ID_Investidor = e.ID_Investidor AND Valor_Retorno_Pagamento > 0  AND c.Valor_Lucro_Pagamento > 0 
                ORDER BY Data DESC
            ");
                
        }

        //Mostra as entradas de lucro apenas
        if ($ID_Conta == $id_conta_lucro) {
            
            $query = $this->db->query("
                SELECT c.ID_Emprestimo, d.ID_Emprestimo_Pai, e.ID_Investidor, e.Nome_Investidor, Valor_Lucro_Pagamento as Valor, c.Data_Pagamento as Data, 'P' as Tipo 
                FROM pagamento c, emprestimo d, investidor e 
                    WHERE c.ID_Emprestimo = d.ID_Emprestimo AND d.ID_Investidor = e.ID_Investidor AND c.Valor_Lucro_Pagamento > 0 
                    ORDER BY Data DESC
            ");
        }
        
        return $query->result_array();
        

    }

    /*
     * function to add new conta
     */
    function add_conta($params)
    {
        $this->db->insert('conta',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update conta
     */
    function update_conta($ID_Conta,$params)
    {
        $this->db->where('ID_Conta',$ID_Conta);
        return $this->db->update('conta',$params);
    }
    
    /*
     * function to delete conta
     */
    function delete_conta($ID_Conta)
    {
        return $this->db->delete('conta',array('ID_Conta'=>$ID_Conta));
    }
}
