<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Observacao_parcela_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get observacao_parcela by ID_Observacao_Parcela
     */
    function get_observacao_parcela($ID_Observacao_Parcela)
    {
        return $this->db->get_where('observacao_parcela',array('ID_Observacao_Parcela'=>$ID_Observacao_Parcela))->row_array();
    }
    
    /*
     * Get all observacao_parcela count
     */
    function get_all_observacao_parcela_count()
    {
        $this->db->from('observacao_parcela');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all observacao_parcela
     */
    function get_all_observacao_parcela($params = array())
    {
        $this->db->order_by('ID_Observacao_Parcela', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('observacao_parcela')->result_array();
    }
        
    /*
     * function to add new observacao_parcela
     */
    function add_observacao_parcela($params)
    {
        $this->db->insert('observacao_parcela',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update observacao_parcela
     */
    function update_observacao_parcela($ID_Observacao_Parcela,$params)
    {
        $this->db->where('ID_Observacao_Parcela',$ID_Observacao_Parcela);
        return $this->db->update('observacao_parcela',$params);
    }
    
    /*
     * function to delete observacao_parcela
     */
    function delete_observacao_parcela($ID_Observacao_Parcela)
    {
        return $this->db->delete('observacao_parcela',array('ID_Observacao_Parcela'=>$ID_Observacao_Parcela));
    }
}
