<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Observacao_emprestimo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get observacao_emprestimo by ID_Observacao
     */
    function get_observacao_emprestimo($ID_Observacao)
    {
        $this->db->join('users','users.id = observacao_emprestimo.ID_User_Create', 'left');
        return $this->db->get_where('observacao_emprestimo',array('ID_Observacao'=>$ID_Observacao))->row_array();
    }
    
    /*
     * Get all observacao_emprestimo count
     */
    function get_all_observacao_emprestimo_count()
    {
        $this->db->join('users','users.id = observacao_emprestimo.ID_User_Create', 'left');
        $this->db->from('observacao_emprestimo');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all observacao_emprestimo
     */
    function get_all_observacao_emprestimo($params = array())
    {
        $this->db->join('users','users.id = observacao_emprestimo.ID_User_Create', 'left');
        $this->db->order_by('ID_Observacao', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('observacao_emprestimo')->result_array();
    }

    /*
     * Get all observacao_emprestimo
     */
    function get_all_observacao_emprestimo_by_parcela($ID_Emprestimo_Parcela)
    {
        $this->db->join('users','users.id = observacao_emprestimo.ID_User_Create', 'left');
        $this->db->where('ID_Emprestimo_Parcela', $ID_Emprestimo_Parcela);
        $this->db->order_by('ID_Observacao', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('observacao_emprestimo')->result_array();
    }

     /*
     * Get all observacao_emprestimo
     */
    function get_all_observacao_emprestimo_by_pai($ID_Emprestimo_Pai)
    {
        $this->db->join('users','users.id = observacao_emprestimo.ID_User_Create', 'left');
        $this->db->where('ID_Emprestimo_Pai', $ID_Emprestimo_Pai);
        $this->db->order_by('ID_Observacao', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('observacao_emprestimo')->result_array();
    }
        
    /*
     * function to add new observacao_emprestimo
     */
    function add_observacao_emprestimo($params)
    {
        $this->db->insert('observacao_emprestimo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update observacao_emprestimo
     */
    function update_observacao_emprestimo($ID_Observacao,$params)
    {
        $this->db->where('ID_Observacao',$ID_Observacao);
        return $this->db->update('observacao_emprestimo',$params);
    }
    
    /*
     * function to delete observacao_emprestimo
     */
    function delete_observacao_emprestimo($ID_Observacao)
    {
        return $this->db->delete('observacao_emprestimo',array('ID_Observacao'=>$ID_Observacao));
    }
}
