<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Renegociacao_parcela_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get renegociacao_parcela by ID_Renegociacao_Parcela
     */
    function get_renegociacao_parcela($ID_Renegociacao_Parcela)
    {
        $this->db->join('forma_pagamento','forma_pagamento.ID_Forma_Pagamento = renegociacao_parcela.ID_Forma_Pagamento','left');
        $this->db->join('observacao_emprestimo','observacao_emprestimo.ID_Parcela = renegociacao_parcela.ID_Renegociacao_Parcela','left');
        $this->db->join('renegociacao','renegociacao.ID_Renegociacao = renegociacao_parcela.ID_Renegociacao','left');
        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo','left');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor','left');
        return $this->db->get_where('renegociacao_parcela',array('ID_Renegociacao_Parcela'=>$ID_Renegociacao_Parcela))->row_array();
    }
    
    /*
     * Get all renegociacao_parcela count
     */
    function get_all_renegociacao_parcela_count()
    {
        $this->db->join('forma_pagamento','forma_pagamento.ID_Forma_Pagamento = renegociacao_parcela.ID_Forma_Pagamento','left');
        $this->db->join('observacao_emprestimo','observacao_emprestimo.ID_Parcela = renegociacao_parcela.ID_Renegociacao_Parcela','left');
        $this->db->join('renegociacao','renegociacao.ID_Renegociacao = renegociacao_parcela.ID_Renegociacao','left');
        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo','left');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor','left');
        $this->db->from('renegociacao_parcela');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all renegociacao_parcela
     */
    function get_all_renegociacao_parcela($params = array())
    {
        $this->db->join('forma_pagamento','forma_pagamento.ID_Forma_Pagamento = renegociacao_parcela.ID_Forma_Pagamento','left');
        $this->db->join('observacao_emprestimo','observacao_emprestimo.ID_Parcela = renegociacao_parcela.ID_Renegociacao_Parcela','left');
        $this->db->join('renegociacao','renegociacao.ID_Renegociacao = renegociacao_parcela.ID_Renegociacao','left');
        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo','left');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor','left');
        $this->db->order_by('Data_Prazo_Parcela', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('renegociacao_parcela')->result_array();
    }

    

    function get_all_parcela_by_renegociacao($ID_Renegociacao) {

        $this->db->join('forma_pagamento','forma_pagamento.ID_Forma_Pagamento = renegociacao_parcela.ID_Forma_Pagamento','left');
        $this->db->join('observacao_emprestimo','observacao_emprestimo.ID_Parcela = renegociacao_parcela.ID_Renegociacao_Parcela','left');
        $this->db->join('renegociacao','renegociacao.ID_Renegociacao = renegociacao_parcela.ID_Renegociacao','left');
        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo','left');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor','left');
        $this->db->where('renegociacao_parcela.ID_Renegociacao', $ID_Renegociacao);
        $this->db->order_by('Data_Prazo_Parcela', 'asc');
        return $this->db->get('renegociacao_parcela')->result_array();

    }

    function get_total_parcela_by_renegociacao($ID_Renegociacao) {

        $this->db->select_sum('Valor_Parcela');
        $this->db->join('forma_pagamento','forma_pagamento.ID_Forma_Pagamento = renegociacao_parcela.ID_Forma_Pagamento','left');
        $this->db->join('observacao_emprestimo','observacao_emprestimo.ID_Parcela = renegociacao_parcela.ID_Renegociacao_Parcela','left');
        $this->db->join('renegociacao','renegociacao.ID_Renegociacao = renegociacao_parcela.ID_Renegociacao','left');
        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo','left');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor','left');
        $this->db->where('renegociacao_parcela.ID_Renegociacao', $ID_Renegociacao);
        $this->db->order_by('Data_Prazo_Parcela', 'asc');
        $objeto = $this->db->get('renegociacao_parcela')->row_array();

        return $objeto['Valor_Parcela'];
        
    }

    function get_total_parcela_pendente_by_renegociacao($ID_Renegociacao) {

        $this->db->select_sum('Valor_Parcela');
        $this->db->join('forma_pagamento','forma_pagamento.ID_Forma_Pagamento = renegociacao_parcela.ID_Forma_Pagamento','left');
        $this->db->join('observacao_emprestimo','observacao_emprestimo.ID_Parcela = renegociacao_parcela.ID_Renegociacao_Parcela','left');
        $this->db->join('renegociacao','renegociacao.ID_Renegociacao = renegociacao_parcela.ID_Renegociacao','left');
        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo','left');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor','left');
        $this->db->where('renegociacao_parcela.ID_Renegociacao', $ID_Renegociacao);
        $this->db->where('renegociacao_parcela.Status_Parcela', '0');
        $this->db->order_by('Data_Prazo_Parcela', 'asc');
        $objeto = $this->db->get('renegociacao_parcela')->row_array();

        return $objeto['Valor_Parcela'];
        
    }
        
    /*
     * function to add new renegociacao_parcela
     */
    function add_renegociacao_parcela($params)
    {
        $this->db->insert('renegociacao_parcela',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update renegociacao_parcela
     */
    function update_renegociacao_parcela($ID_Renegociacao_Parcela,$params)
    {
        $this->db->where('ID_Renegociacao_Parcela',$ID_Renegociacao_Parcela);
        return $this->db->update('renegociacao_parcela',$params);
    }
    
    /*
     * function to delete renegociacao_parcela
     */
    function delete_renegociacao_parcela($ID_Renegociacao_Parcela)
    {
        return $this->db->delete('renegociacao_parcela',array('ID_Renegociacao_Parcela'=>$ID_Renegociacao_Parcela));
    }

    function delete_parcelas_by_renegociacao($ID_Renegociacao) {
        return $this->db->delete('renegociacao_parcela',array('ID_Renegociacao'=>$ID_Renegociacao));
    }
}
