<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Renegociacao_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get renegociacao by ID_Renegociacao
     */
    function get_renegociacao($ID_Renegociacao)
    {
        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo', 'join');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor', 'join');
        return $this->db->get_where('renegociacao',array('ID_Renegociacao'=>$ID_Renegociacao))->row_array();
    }
    
    /*
     * Get all renegociacao count
     */
    function get_all_renegociacao_count()
    {
        $this->db->from('renegociacao');
        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo', 'join');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor', 'join');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all renegociacao
     */
    function get_all_renegociacao($params = array())
    {

        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo', 'join');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor', 'join');
        $this->db->order_by('ID_Renegociacao', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('renegociacao')->result_array();
    }

    function get_all_renegociacao_by_emprestimo($ID_Emprestimo)
    {

        $this->db->join('emprestimo','emprestimo.ID_Emprestimo = renegociacao.ID_Emprestimo', 'join');
        $this->db->join('investidor','investidor.ID_Investidor = emprestimo.ID_Investidor', 'join');
        $this->db->where('renegociacao.ID_Emprestimo', $ID_Emprestimo);
        $this->db->order_by('renegociacao.ID_Renegociacao', 'desc');
        return $this->db->get('renegociacao')->result_array();
    }
        
    /*
     * function to add new renegociacao
     */
    function add_renegociacao($params)
    {
        $this->db->insert('renegociacao',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update renegociacao
     */
    function update_renegociacao($ID_Renegociacao,$params)
    {
        $this->db->where('ID_Renegociacao',$ID_Renegociacao);
        return $this->db->update('renegociacao',$params);
    }
    
    /*
     * function to delete renegociacao
     */
    function delete_renegociacao($ID_Renegociacao)
    {
        return $this->db->delete('renegociacao',array('ID_Renegociacao'=>$ID_Renegociacao));
    }

    function delete_renegociacao_by_emprestimo($ID_Emprestimo) {
        return $this->db->delete('renegociacao',array('ID_Emprestimo'=>$ID_Emprestimo));
    }
}
